version: "3"

services:
  app:
    build: .
  nginx:
    image: nginx:1.22
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/somas.godata.id:/etc/letsencrypt/live/somas.godata.id